In [1]:
import pandas as pd
import requests
import numpy as np
import http.client, urllib.parse
import json

In [80]:
df = pd.read_csv('plane_crash.csv', encoding='unicode_escape', index_col = 0)
#df.replace('', np)
#df.replace('nan', np.NaN)
df = df.fillna('')


df['Location'] = df['Location'].str.replace('Near', '').str.replace('Off', '').str.strip()

In [64]:
df

,Date,Time,Location,Operator,Flight..,Route,AC.Type,Registration,cn.ln,Aboard,Aboard.Passangers,Aboard.Crew,Fatalities,Fatalities.Passangers,Fatalities.Crew,Ground,Summary
1,09/17/1908,17:18,"Fort Myer, Virginia",Military - U.S. Army,NaN,Demonstration,Wright Flyer III,NaN,1,2.0,1.0,1.0,1.0,1.0,0.0,0.0,"During a demonstration flight, a U.S. Army fly..."
2,09/07/1909,NaN,"Juvisy-sur-Orge, France",NaN,NaN,Air show,Wright Byplane,SC1,NaN,1.0,0.0,1.0,1.0,0.0,0.0,0.0,Eugene Lefebvre was the first pilot to ever be...
3,07/12/1912,06:30,"Atlantic City, New Jersey",Military - U.S. Navy,NaN,Test flight,Dirigible,NaN,NaN,5.0,0.0,5.0,5.0,0.0,5.0,0.0,First U.S. dirigible Akron exploded just offsh...
4,08/06/1913,NaN,"Victoria, British Columbia, Canada",Private,NaN,NaN,Curtiss seaplane,NaN,NaN,1.0,0.0,1.0,1.0,0.0,1.0,0.0,The first fatal airplane accident in Canada oc...
5,09/09/1913,18:30,Over the North Sea,Military - German Navy,NaN,NaN,Zeppelin L-1 (airship),NaN,NaN,20.0,NaN,NaN,14.0,NaN,NaN,0.0,The airship flew into a thunderstorm and encou...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33100,07/16/2022,22:47,"Eleftheroupolis, Greece",Meridian,MEM3032,Nis- Amman,Antonov An-12,UR-CIC,01347701,8.0,0.0,8.0,8.0,0.0,8.0,0.0,The cargo plane carrying eight crew members an...
34100,11/06/2022,08:53,"Bukoba, Tanzania",Precision Air,PW494,Dar es-Salaam -Bukoba,ATR 42-500,5H-PWF,819,43.0,39.0,39.0,19.0,17.0,2.0,0.0,"While on final approach to Bukoba Airport, the..."
35100,11/18/2022,15:11,"Lima, Peru",LATAM,LA2213,Lima - Juliaca,Airbus 320-271N,CC-BHB,7864,108.0,102.0,6.0,0.0,0.0,0.0,2.0,The Airbus A320 collided with a fire truck whi...
36100,11/21/2022,10:15,"Medellín, Colombia",AeroPaca SAS,NaN,Medellín - Pizarro,Piper PA-31-350 Navajo Chieftain,HK-5121,31-7652004,8.0,6.0,2.0,8.0,6.0,2.0,0.0,The plane was chartered to carry a team of six...
37100,01/15/2023,10:50,"Pokhara, Nepal",Yeti Airlines,YT691,Kathmandu - Pokhara,ATR 72-500-72-212-A,9NANC,754,72.0,68.0,4.0,72.0,68.0,4.0,0.0,"Before approach, the pilot requested a change ..."

In [19]:
def get_coordinates(location):
    
    url = 'https://api.positionstack.com/v1/forward?'
    
    
    params = {'access_key': 'c2eeab87a4caca6efddfddae36b56875',
    'query': ,
    'limit': 1,
    }
    
    
    data = requests.get(url = url, params=params).text
    
    
    return data

get_coordinates('denmark')

'{"error":{"code":"https_access_restricted","message":"Access Restricted - Your current Subscription Plan does not support HTTPS Encryption."}}'

In [55]:
def get_coordinates(location):    
    conn = http.client.HTTPConnection('api.positionstack.com')

    params = urllib.parse.urlencode({
    'access_key': 'c2eeab87a4caca6efddfddae36b56875',
    'query': location,
    'limit': 1,
    })

    conn.request('GET', '/v1/forward?{}'.format(params))

    res = conn.getresponse()
    data = res.read().decode('utf-8')
    data = json.loads(data)
    
    try:
        lat = data['data'][0]['latitude']
        lon = data['data'][0]['longitude']
        
    except:
        lat = ''
        lon = ''
    
    return lat, lon

In [82]:
for index, row in df.iterrows():
    
    location = row['Location']
    
    #location = location.split(',')[0]
    
    #if location == ['Off']
    
    if type(location) == float:
        print(location)
        #print(get_coordinates(row['Location']))

In [83]:
df['Coordinates'] = df['Location'].map(lambda x: get_coordinates(x.split(',')[0]))

In [26]:
df = pd.read_csv('../data/plane_crash_coordinates.csv')
df = df.assign(Longitude='', Latitude='')

In [25]:
df.columns

AttributeError: 'str' object has no attribute 'columns'

In [34]:
for _, row in df.iterrows():

    coordinates = row['Coordinates']
    coordinates = coordinates.replace('(','').replace(')','')
    coordinatesTuple = tuple(coordinates.split(', '))
    
    lat, lon = coordinatesTuple    
    
    df.at[_, 'Latitude'] = lat
    df.at[_, 'Longitude'] = lon

In [35]:
df

,Unnamed: 0,Date,Time,Location,Operator,Flight..,Route,AC.Type,Registration,cn.ln,...,Aboard.Passangers,Aboard.Crew,Fatalities,Fatalities.Passangers,Fatalities.Crew,Ground,Summary,Coordinates,Longitude,Latitude
0,1,09/17/1908,17:18,"Fort Myer, Virginia",Military - U.S. Army,NaN,Demonstration,Wright Flyer III,NaN,1,...,1.0,1.0,1.0,1.0,0.0,0.0,"During a demonstration flight, a U.S. Army fly...","(38.878877, -77.068158)",-77.068158,38.878877
1,2,09/07/1909,NaN,"Juvisy-sur-Orge, France",NaN,NaN,Air show,Wright Byplane,SC1,NaN,...,0.0,1.0,1.0,0.0,0.0,0.0,Eugene Lefebvre was the first pilot to ever be...,"(48.691161, 2.374077)",2.374077,48.691161
2,3,07/12/1912,06:30,"Atlantic City, New Jersey",Military - U.S. Navy,NaN,Test flight,Dirigible,NaN,NaN,...,0.0,5.0,5.0,0.0,5.0,0.0,First U.S. dirigible Akron exploded just offsh...,"(39.377094, -74.451563)",-74.451563,39.377094
3,4,08/06/1913,NaN,"Victoria, British Columbia, Canada",Private,NaN,NaN,Curtiss seaplane,NaN,NaN,...,0.0,1.0,1.0,0.0,1.0,0.0,The first fatal airplane accident in Canada oc...,"(22.381131, 114.135572)",114.135572,22.381131
4,5,09/09/1913,18:30,Over the North Sea,Military - German Navy,NaN,NaN,Zeppelin L-1 (airship),NaN,NaN,...,NaN,NaN,14.0,NaN,NaN,0.0,The airship flew into a thunderstorm and encou...,"(15.530675, 73.764707)",73.764707,15.530675
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4989,33100,07/16/2022,22:47,"Eleftheroupolis, Greece",Meridian,MEM3032,Nis- Amman,Antonov An-12,UR-CIC,01347701,...,0.0,8.0,8.0,0.0,8.0,0.0,The cargo plane carrying eight crew members an...,"(40.91389, 24.25139)",24.25139,40.91389
4990,34100,11/06/2022,08:53,"Bukoba, Tanzania",Precision Air,PW494,Dar es-Salaam -Bukoba,ATR 42-500,5H-PWF,819,...,39.0,39.0,19.0,17.0,2.0,0.0,"While on final approach to Bukoba Airport, the...","(-1.414912, 31.654234)",31.654234,-1.414912
4991,35100,11/18/2022,15:11,"Lima, Peru",LATAM,LA2213,Lima - Juliaca,Airbus 320-271N,CC-BHB,7864,...,102.0,6.0,0.0,0.0,0.0,2.0,The Airbus A320 collided with a fire truck whi...,"(-12.049141, -77.021217)",-77.021217,-12.049141
4992,36100,11/21/2022,10:15,"Medellín, Colombia",AeroPaca SAS,NaN,Medellín - Pizarro,Piper PA-31-350 Navajo Chieftain,HK-5121,31-7652004,...,6.0,2.0,8.0,6.0,2.0,0.0,The plane was chartered to carry a team of six...,"(6.276949, -75.576955)",-75.576955,6.276949
4993,37100,01/15/2023,10:50,"Pokhara, Nepal",Yeti Airlines,YT691,Kathmandu - Pokhara,ATR 72-500-72-212-A,9NANC,754,...,68.0,4.0,72.0,68.0,4.0,0.0,"Before approach, the pilot requested a change ...","(28.26689, 83.96851)",83.96851,28.26689